#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Transparent ML Intro
author                      : Haiping Lu and Shuo Zhou # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : transparentml-logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 300


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: intro-transparent-ml.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/pykale/transparentML  # Online location of your book
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  use_multitoc_numbering: true

# Add launch buttons
# See https://jupyterbook.org/en/stable/interactive/launchbuttons.html
launch_buttons:
# Google Colab links will only work for pages that have the .ipynb extension.
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    # Get help to make the width more flexible, wider on wide screen. May need help from Sina
    # html_js_files:
    # - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # html_css_files: ???
    bibtex_reference_style: author_year

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
